
OBJS := $(OBJS) game/object.o game/world.o game/player.o game/sections.o \
    game/objects.o game/explode.o game/bullet.o game/enemy.o game/script.o \
    game/pbullet.o game/ebullet.o \
    game/checkpnt.o game/stageend.o game/setspeed.o \
    game/box.o game/mbox.o \
    game/enemy/shard.o game/enemy/gunboat.o \
    game/diffic.o game/stage.o game/game.o
