
OBJS := $(OBJS) game/object.o game/world.o game/player.o game/sections.o \
    game/objects.o game/explode.o game/bullet.o game/enemy.o game/script.o \
    game/box.o game/mbox.o game/pbullet.o game/checkpnt.o game/stageend.o \
    game/stage.o game/game.o
