
OBJS := $(OBJS) game/object.o game/world.o game/player.o game/sections.o \
    game/objects.o game/explode.o game/bullet.o game/enemy.o game/script.o \
    game/obstacle.o \
    game/pbullet.o game/ebullet.o \
    game/checkpnt.o game/stageend.o game/setspeed.o \
    game/box.o game/sbox.o game/enemy/mbox.o \
    game/enemy/shard.o game/enemy/gunboat.o game/enemy/volcano.o \
    game/enemy/chevron.o game/enemy/fighter.o game/enemy/wave.o \
    game/enemy/turret.o game/enemy/boss0.o game/enemy/boss1.o \
    game/enemy/walker.o game/enemy/spider.o game/enemy/gunboat2.o
    game/diffic.o game/stage.o game/nameentr.o game/game.o
