
OBJS := $(OBJS) \
	menu/menu.o menu/menugame.o menu/menuvid.o menu/menuaud.o menu/menuinp.o \
	menu/menuinpb.o menu/menuyn.o menu/menuopt.o menu/menuhigh.o \
	menu/menuhelp.o menu/menumain.o menu/menupaus.o
