
OBJS := $(OBJS) \
	main/file.o main/logger.o main/config.o main/assets.o main/video.o \
	main/audio.o main/input.o main/logic.o main/mholder.o main/buttons.o \
	main/gconfig.o main/random.o main/scores.o main/collide.o main/sys.o \
	main/hiemalia.o
